//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAL_AKTIV
    {
        public decimal ID { get; set; }
        public string NICK { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> OLD_YEAR { get; set; }
        public Nullable<decimal> CURRENT_YEAR { get; set; }
        public Nullable<decimal> KOREKTIV { get; set; }
    }
}
