//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_PART
    {
        public GROUP_PART()
        {
            this.KNTR_GRP_PART_PRICE = new HashSet<KNTR_GRP_PART_PRICE>();
        }
    
        public int ID { get; set; }
        public Nullable<short> LVL { get; set; }
        public Nullable<int> OWNER_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<KNTR_GRP_PART_PRICE> KNTR_GRP_PART_PRICE { get; set; }
    }
}
