//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COUNTRIES> COUNTRIES { get; set; }
        public DbSet<DEPARTMENTS> DEPARTMENTS { get; set; }
        public DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public DbSet<JOB_HISTORY> JOB_HISTORY { get; set; }
        public DbSet<JOBS> JOBS { get; set; }
        public DbSet<LOCATIONS> LOCATIONS { get; set; }
        public DbSet<REGIONS> REGIONS { get; set; }
        public DbSet<EMP_DETAILS_VIEW> EMP_DETAILS_VIEW { get; set; }
    
        public virtual int ADD_JOB_HISTORY(Nullable<decimal> p_EMP_ID, Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE, string p_JOB_ID, Nullable<decimal> p_DEPARTMENT_ID)
        {
            var p_EMP_IDParameter = p_EMP_ID.HasValue ?
                new ObjectParameter("P_EMP_ID", p_EMP_ID) :
                new ObjectParameter("P_EMP_ID", typeof(decimal));
    
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_JOB_IDParameter = p_JOB_ID != null ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(string));
    
            var p_DEPARTMENT_IDParameter = p_DEPARTMENT_ID.HasValue ?
                new ObjectParameter("P_DEPARTMENT_ID", p_DEPARTMENT_ID) :
                new ObjectParameter("P_DEPARTMENT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_JOB_HISTORY", p_EMP_IDParameter, p_START_DATEParameter, p_END_DATEParameter, p_JOB_IDParameter, p_DEPARTMENT_IDParameter);
        }
    
        public virtual int INSERT_EMPLOYEE(string fIRST_NAME, string lAST_NAME, string eMAIL, string pHONE_NUMBER, Nullable<System.DateTime> hIRE_DATE, string jOB_ID, Nullable<decimal> sALARY, Nullable<decimal> cOMMISSION_PCT, Nullable<decimal> mANAGER_ID, Nullable<decimal> dEPARTMENT_ID)
        {
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pHONE_NUMBERParameter = pHONE_NUMBER != null ?
                new ObjectParameter("PHONE_NUMBER", pHONE_NUMBER) :
                new ObjectParameter("PHONE_NUMBER", typeof(string));
    
            var hIRE_DATEParameter = hIRE_DATE.HasValue ?
                new ObjectParameter("HIRE_DATE", hIRE_DATE) :
                new ObjectParameter("HIRE_DATE", typeof(System.DateTime));
    
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            var sALARYParameter = sALARY.HasValue ?
                new ObjectParameter("SALARY", sALARY) :
                new ObjectParameter("SALARY", typeof(decimal));
    
            var cOMMISSION_PCTParameter = cOMMISSION_PCT.HasValue ?
                new ObjectParameter("COMMISSION_PCT", cOMMISSION_PCT) :
                new ObjectParameter("COMMISSION_PCT", typeof(decimal));
    
            var mANAGER_IDParameter = mANAGER_ID.HasValue ?
                new ObjectParameter("MANAGER_ID", mANAGER_ID) :
                new ObjectParameter("MANAGER_ID", typeof(decimal));
    
            var dEPARTMENT_IDParameter = dEPARTMENT_ID.HasValue ?
                new ObjectParameter("DEPARTMENT_ID", dEPARTMENT_ID) :
                new ObjectParameter("DEPARTMENT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EMPLOYEE", fIRST_NAMEParameter, lAST_NAMEParameter, eMAILParameter, pHONE_NUMBERParameter, hIRE_DATEParameter, jOB_IDParameter, sALARYParameter, cOMMISSION_PCTParameter, mANAGER_IDParameter, dEPARTMENT_IDParameter);
        }
    
        public virtual int SECURE_DML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SECURE_DML");
        }
    
        public virtual int UPDATE_AND_RETURN_SALARY(Nullable<decimal> eMPID, Nullable<decimal> rAISE)
        {
            var eMPIDParameter = eMPID.HasValue ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(decimal));
    
            var rAISEParameter = rAISE.HasValue ?
                new ObjectParameter("RAISE", rAISE) :
                new ObjectParameter("RAISE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_AND_RETURN_SALARY", eMPIDParameter, rAISEParameter);
        }
    
        public virtual int UPDATE_AND_RETURN_SALARY_BINDV(Nullable<decimal> eMPID, Nullable<decimal> rAISE, ObjectParameter nEWSAL)
        {
            var eMPIDParameter = eMPID.HasValue ?
                new ObjectParameter("EMPID", eMPID) :
                new ObjectParameter("EMPID", typeof(decimal));
    
            var rAISEParameter = rAISE.HasValue ?
                new ObjectParameter("RAISE", rAISE) :
                new ObjectParameter("RAISE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_AND_RETURN_SALARY_BINDV", eMPIDParameter, rAISEParameter, nEWSAL);
        }
    }
}
