//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_OPR
    {
        public KASA_OPR()
        {
            this.KASA_OPR_ITEM = new HashSet<KASA_OPR_ITEM>();
        }
    
        public int KOD { get; set; }
        public string IME { get; set; }
        public string TYPE_DOC { get; set; }
        public Nullable<short> PAPKA { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<KASA_OPR_ITEM> KASA_OPR_ITEM { get; set; }
    }
}
