//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_DOCACC
    {
        public string NODOC { get; set; }
        public short POS { get; set; }
        public Nullable<decimal> ID { get; set; }
        public string PARTIDA { get; set; }
    
        public virtual KASA_DOC KASA_DOC { get; set; }
    }
}
