//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNTR_GRP_PART_PRICE
    {
        public int GROUP_PART_ID { get; set; }
        public int KONTRAGENT_KOD { get; set; }
        public Nullable<decimal> PRCNT { get; set; }
    
        public virtual GROUP_PART GROUP_PART { get; set; }
    }
}
