//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTRAGENT
    {
        public string IS_CLI { get; set; }
        public string IS_KONS { get; set; }
        public string IS_DOST { get; set; }
        public string IS_INP { get; set; }
        public string IS_SKL { get; set; }
        public int KOD { get; set; }
        public string IME { get; set; }
        public string ADR { get; set; }
        public string DANNO { get; set; }
        public string BULSTAT { get; set; }
        public string MOL { get; set; }
        public string MOLPOL { get; set; }
        public string MOLLP { get; set; }
        public string MOLPALNOM { get; set; }
        public string DIG_CODE { get; set; }
        public string TEL { get; set; }
        public Nullable<decimal> OTSTAPKA { get; set; }
        public string ZABEL { get; set; }
        public Nullable<int> KOD2 { get; set; }
        public string IS_AKCIZ { get; set; }
    }
}
