//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_COMM_ITEM
    {
        public decimal NOM_CODE { get; set; }
        public decimal CODE { get; set; }
        public string NAME { get; set; }
    
        public virtual NOM_COMM NOM_COMM { get; set; }
    }
}
