//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPRITEM
    {
        public int ID { get; set; }
        public Nullable<short> STATIA { get; set; }
        public string D_K { get; set; }
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<decimal> ST_VAL { get; set; }
        public Nullable<decimal> ST_LV { get; set; }
        public Nullable<decimal> K_VO { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string TXT { get; set; }
        public short POS { get; set; }
        public string M_KA { get; set; }
        public string DK_STATUS { get; set; }
    
        public virtual DNEVNIK_DDS DNEVNIK_DDS { get; set; }
        public virtual OPR OPR { get; set; }
    }
}
