//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREDNAZ_DA
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string SMETKA_DT { get; set; }
        public string SMETKA_KT { get; set; }
    }
}
