//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODAGBI_DDS
    {
        public string USER_NAME { get; set; }
        public string C_02_00_01 { get; set; }
        public string C_02_01_02 { get; set; }
        public string C_02_02_03 { get; set; }
        public string C_02_03_04 { get; set; }
        public string C_02_04_05 { get; set; }
        public string C_02_05_06 { get; set; }
        public string C_02_06_07 { get; set; }
        public string C_02_07_08 { get; set; }
        public string C_02_08_09 { get; set; }
        public string C_02_09_10 { get; set; }
        public Nullable<decimal> C_02_10_11 { get; set; }
        public Nullable<decimal> C_02_20_12 { get; set; }
        public Nullable<decimal> C_02_11_13 { get; set; }
        public Nullable<decimal> C_02_21_14 { get; set; }
        public Nullable<decimal> C_02_12_15 { get; set; }
        public Nullable<decimal> C_02_26_16 { get; set; }
        public Nullable<decimal> C_02_22_17 { get; set; }
        public Nullable<decimal> C_02_23_18 { get; set; }
        public Nullable<decimal> C_02_13_19 { get; set; }
        public Nullable<decimal> C_02_24_20 { get; set; }
        public Nullable<decimal> C_02_14_21 { get; set; }
        public Nullable<decimal> C_02_15_21 { get; set; }
        public Nullable<decimal> C_02_16_22 { get; set; }
        public Nullable<decimal> C_02_17_23 { get; set; }
        public Nullable<decimal> C_02_18_24 { get; set; }
        public Nullable<decimal> C_02_19_25 { get; set; }
        public Nullable<decimal> C_02_25_26 { get; set; }
        public Nullable<decimal> OPR_ID { get; set; }
    }
}
