//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAZHSING
    {
        public string NOM_DOC { get; set; }
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<decimal> K_VO { get; set; }
        public Nullable<decimal> ST_LV { get; set; }
    }
}
