//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVAL_DA
    {
        public string SMETKA { get; set; }
        public System.DateTime BEGIN_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public Nullable<decimal> KOEF { get; set; }
    }
}
