//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIZIA_ITEM
    {
        public int ID { get; set; }
        public string PARTNUMBER { get; set; }
        public Nullable<decimal> K_VO { get; set; }
        public decimal POS { get; set; }
    
        public virtual REVIZIA REVIZIA { get; set; }
    }
}
