//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIZIA
    {
        public REVIZIA()
        {
            this.REVIZIA_ITEM = new HashSet<REVIZIA_ITEM>();
            this.REVIZIA_PARTIDA = new HashSet<REVIZIA_PARTIDA>();
        }
    
        public int ID { get; set; }
        public string NOM_DOC { get; set; }
        public Nullable<System.DateTime> DATE_DOC { get; set; }
        public string DESCRIPTION { get; set; }
        public string SMETKA { get; set; }
    
        public virtual ICollection<REVIZIA_ITEM> REVIZIA_ITEM { get; set; }
        public virtual ICollection<REVIZIA_PARTIDA> REVIZIA_PARTIDA { get; set; }
    }
}
