//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVISE
    {
        public int SERVISE_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string FIRMA { get; set; }
        public string KONTAKT { get; set; }
        public string TEL { get; set; }
    }
}
