//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINTSMET
    {
        public SINTSMET()
        {
            this.SINTSMET_ANPOK = new HashSet<SINTSMET_ANPOK>();
        }
    
        public string SMETKA { get; set; }
        public string NAME { get; set; }
        public string IS_BAL { get; set; }
        public string HAR { get; set; }
        public string IS_ANAL { get; set; }
        public string IS_VAL { get; set; }
        public string IS_VAL_ANAL { get; set; }
        public string VAL_KOD { get; set; }
        public string IS_EXT_SALD { get; set; }
        public string IS_K_VO { get; set; }
        public Nullable<int> ID_K_VO { get; set; }
        public string IS_KOREKTIV { get; set; }
        public string IS_TRANSIT { get; set; }
        public string IS_PURGE_OBOROT { get; set; }
        public string M_KA { get; set; }
    
        public virtual ICollection<SINTSMET_ANPOK> SINTSMET_ANPOK { get; set; }
    }
}
