//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMETKA_SMETKA
    {
        public SMETKA_SMETKA()
        {
            this.SMETKA_SMETKA_ITEM = new HashSet<SMETKA_SMETKA_ITEM>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SMETKA1 { get; set; }
        public string SMETKA2 { get; set; }
    
        public virtual ICollection<SMETKA_SMETKA_ITEM> SMETKA_SMETKA_ITEM { get; set; }
    }
}
