//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.orders = new HashSet<order>();
        }
    
        public int idstatus { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
