//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StZagoraEntities : DbContext
    {
        public StZagoraEntities()
            : base("name=StZagoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANALSMET> ANALSMET { get; set; }
        public DbSet<ANPOK> ANPOK { get; set; }
        public DbSet<ANPOKITEM> ANPOKITEM { get; set; }
        public DbSet<BAL_AKTIV> BAL_AKTIV { get; set; }
        public DbSet<BAL_PASIV> BAL_PASIV { get; set; }
        public DbSet<BARCODE> BARCODE { get; set; }
        public DbSet<CENI> CENI { get; set; }
        public DbSet<DDS_ETIKET> DDS_ETIKET { get; set; }
        public DbSet<DECL_DDS> DECL_DDS { get; set; }
        public DbSet<DNEVNIK_DDS> DNEVNIK_DDS { get; set; }
        public DbSet<DOC> DOC { get; set; }
        public DbSet<DOCACC> DOCACC { get; set; }
        public DbSet<DOCACCSTORE> DOCACCSTORE { get; set; }
        public DbSet<GAR_KARTA> GAR_KARTA { get; set; }
        public DbSet<GAR_PRINT> GAR_PRINT { get; set; }
        public DbSet<GROUP_PART> GROUP_PART { get; set; }
        public DbSet<INV_BOOK> INV_BOOK { get; set; }
        public DbSet<ITEM_DOC_RIGHTS> ITEM_DOC_RIGHTS { get; set; }
        public DbSet<ITEM_KLI_RIGHTS> ITEM_KLI_RIGHTS { get; set; }
        public DbSet<ITEM_RIGHTS> ITEM_RIGHTS { get; set; }
        public DbSet<IZDELIE> IZDELIE { get; set; }
        public DbSet<IZDELIE_ITEM> IZDELIE_ITEM { get; set; }
        public DbSet<KASA> KASA { get; set; }
        public DbSet<KASA_DOC> KASA_DOC { get; set; }
        public DbSet<KASA_DOCACC> KASA_DOCACC { get; set; }
        public DbSet<KASA_ITEM> KASA_ITEM { get; set; }
        public DbSet<KASA_OPR> KASA_OPR { get; set; }
        public DbSet<KASA_OPR_ITEM> KASA_OPR_ITEM { get; set; }
        public DbSet<KNTR_GRP_PART_PRICE> KNTR_GRP_PART_PRICE { get; set; }
        public DbSet<KONTRAGENT> KONTRAGENT { get; set; }
        public DbSet<KONTRAGENT_PART_PRICE> KONTRAGENT_PART_PRICE { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<NOM_COMM> NOM_COMM { get; set; }
        public DbSet<NOM_COMM_ITEM> NOM_COMM_ITEM { get; set; }
        public DbSet<OPP> OPP { get; set; }
        public DbSet<OPR> OPR { get; set; }
        public DbSet<OPR_PRIHOD> OPR_PRIHOD { get; set; }
        public DbSet<OPR_RAZHOD> OPR_RAZHOD { get; set; }
        public DbSet<OPRITEM> OPRITEM { get; set; }
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<ORDERS_ITEM> ORDERS_ITEM { get; set; }
        public DbSet<PART> PART { get; set; }
        public DbSet<PART_EQU> PART_EQU { get; set; }
        public DbSet<PART_LOG> PART_LOG { get; set; }
        public DbSet<PARTITEM> PARTITEM { get; set; }
        public DbSet<PARTMETRO> PARTMETRO { get; set; }
        public DbSet<PAY_KONTR> PAY_KONTR { get; set; }
        public DbSet<PBCATCOL> PBCATCOL { get; set; }
        public DbSet<PBCATFMT> PBCATFMT { get; set; }
        public DbSet<PBCATTBL> PBCATTBL { get; set; }
        public DbSet<POKUPKI_DDS> POKUPKI_DDS { get; set; }
        public DbSet<PREDNAZ_DA> PREDNAZ_DA { get; set; }
        public DbSet<PREKLU> PREKLU { get; set; }
        public DbSet<PRODAGBI_DDS> PRODAGBI_DDS { get; set; }
        public DbSet<PRODUCTION> PRODUCTION { get; set; }
        public DbSet<RAZH> RAZH { get; set; }
        public DbSet<RAZHITEM> RAZHITEM { get; set; }
        public DbSet<RAZHSING> RAZHSING { get; set; }
        public DbSet<RAZP> RAZP { get; set; }
        public DbSet<RAZPITEM> RAZPITEM { get; set; }
        public DbSet<RAZPSTORE> RAZPSTORE { get; set; }
        public DbSet<REG_USER> REG_USER { get; set; }
        public DbSet<REVAL_DA> REVAL_DA { get; set; }
        public DbSet<REVIZIA> REVIZIA { get; set; }
        public DbSet<REVIZIA_ITEM> REVIZIA_ITEM { get; set; }
        public DbSet<REVIZIA_PARTIDA> REVIZIA_PARTIDA { get; set; }
        public DbSet<SALDA> SALDA { get; set; }
        public DbSet<SALDA_NEG> SALDA_NEG { get; set; }
        public DbSet<SCET_STAT> SCET_STAT { get; set; }
        public DbSet<SCET_STAT_ITEM> SCET_STAT_ITEM { get; set; }
        public DbSet<SEARCHSQL> SEARCHSQL { get; set; }
        public DbSet<SEQ_FREE> SEQ_FREE { get; set; }
        public DbSet<SEQ_GEN> SEQ_GEN { get; set; }
        public DbSet<SERVISE> SERVISE { get; set; }
        public DbSet<SINTSMET> SINTSMET { get; set; }
        public DbSet<SINTSMET_ANPOK> SINTSMET_ANPOK { get; set; }
        public DbSet<SMETKA_SMETKA> SMETKA_SMETKA { get; set; }
        public DbSet<SMETKA_SMETKA_ITEM> SMETKA_SMETKA_ITEM { get; set; }
        public DbSet<STGRUPI> STGRUPI { get; set; }
        public DbSet<TDNEVNIK_DDS> TDNEVNIK_DDS { get; set; }
        public DbSet<TDOC_CU> TDOC_CU { get; set; }
        public DbSet<TDOCACC> TDOCACC { get; set; }
        public DbSet<TDOCACC_CU> TDOCACC_CU { get; set; }
        public DbSet<TINSDOC> TINSDOC { get; set; }
        public DbSet<TINSOPR> TINSOPR { get; set; }
        public DbSet<TOPR> TOPR { get; set; }
        public DbSet<TOPRITEM> TOPRITEM { get; set; }
        public DbSet<TPART> TPART { get; set; }
        public DbSet<TPART_POL> TPART_POL { get; set; }
        public DbSet<TPARTINS> TPARTINS { get; set; }
        public DbSet<VAL> VAL { get; set; }
        public DbSet<VALKURS> VALKURS { get; set; }
        public DbSet<VID_DA> VID_DA { get; set; }
        public DbSet<VIES_DDS> VIES_DDS { get; set; }
        public DbSet<VIES_DDS_SEC_05> VIES_DDS_SEC_05 { get; set; }
        public DbSet<VNOS> VNOS { get; set; }
        public DbSet<VNOSINVOICE> VNOSINVOICE { get; set; }
        public DbSet<VNOSNOMRAZH> VNOSNOMRAZH { get; set; }
        public DbSet<VNOSRAZHODI> VNOSRAZHODI { get; set; }
        public DbSet<ZAPRH_IZDELIE> ZAPRH_IZDELIE { get; set; }
        public DbSet<ZAPRH_IZDELIE_ITEM> ZAPRH_IZDELIE_ITEM { get; set; }
        public DbSet<HEAD_BOOK> HEAD_BOOK { get; set; }
        public DbSet<V_HEAD_BOOK> V_HEAD_BOOK { get; set; }
    }
}
