//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HEAD_BOOK
    {
        public int ID { get; set; }
        public string NOM_DOC { get; set; }
        public Nullable<System.DateTime> DATE_DOC { get; set; }
        public string TYPE_DOC { get; set; }
        public Nullable<int> PAPKA { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> VALEUR { get; set; }
        public string O1_D_K { get; set; }
        public string O1_SMETKA { get; set; }
        public string O1_PARTIDA { get; set; }
        public Nullable<decimal> O1_K_VO { get; set; }
        public Nullable<decimal> O1_ST_VAL { get; set; }
        public Nullable<decimal> O1_ST_LV { get; set; }
        public string O1_TXT { get; set; }
        public Nullable<short> O1_STATIA { get; set; }
        public short O1_POS { get; set; }
        public string O2_D_K { get; set; }
        public string O2_SMETKA { get; set; }
        public string O2_PARTIDA { get; set; }
        public Nullable<decimal> O2_K_VO { get; set; }
        public Nullable<decimal> O2_ST_VAL { get; set; }
        public Nullable<decimal> O2_ST_LV { get; set; }
        public string O2_TXT { get; set; }
        public Nullable<short> O2_STATIA { get; set; }
        public short O2_POS { get; set; }
        public Nullable<decimal> CNT { get; set; }
    }
}
