//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAL
    {
        public VAL()
        {
            this.VALKURS = new HashSet<VALKURS>();
        }
    
        public string DIG_CODE { get; set; }
        public string BANK_CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> FOR_BY { get; set; }
    
        public virtual ICollection<VALKURS> VALKURS { get; set; }
    }
}
