//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALSMET
    {
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public string HAR { get; set; }
        public string IS_CLOSED { get; set; }
        public Nullable<System.DateTime> OPEN_DATE { get; set; }
        public string OPEN_USR_NUM { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string CLOSE_USR_NUM { get; set; }
        public string M_KA { get; set; }
        public Nullable<int> S_CODE { get; set; }
        public Nullable<int> S_CODE2 { get; set; }
        public Nullable<int> S_CODE3 { get; set; }
    }
}
