//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANPOK
    {
        public ANPOK()
        {
            this.ANPOKITEM = new HashSet<ANPOKITEM>();
            this.SINTSMET_ANPOK = new HashSet<SINTSMET_ANPOK>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> N_SIZE { get; set; }
    
        public virtual ICollection<ANPOKITEM> ANPOKITEM { get; set; }
        public virtual ICollection<SINTSMET_ANPOK> SINTSMET_ANPOK { get; set; }
    }
}
