//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECL_DDS
    {
        public string USER_NAME { get; set; }
        public string C_00_01 { get; set; }
        public string C_00_02 { get; set; }
        public string C_00_03 { get; set; }
        public string C_00_04 { get; set; }
        public Nullable<long> C_00_05 { get; set; }
        public Nullable<long> C_00_06 { get; set; }
        public Nullable<decimal> C_01_01 { get; set; }
        public Nullable<decimal> C_01_20 { get; set; }
        public Nullable<decimal> C_01_11 { get; set; }
        public Nullable<decimal> C_01_21 { get; set; }
        public Nullable<decimal> C_01_12 { get; set; }
        public Nullable<decimal> C_01_22 { get; set; }
        public Nullable<decimal> C_01_23 { get; set; }
        public Nullable<decimal> C_01_13 { get; set; }
        public Nullable<decimal> C_01_24 { get; set; }
        public Nullable<decimal> C_01_14 { get; set; }
        public Nullable<decimal> C_01_15 { get; set; }
        public Nullable<decimal> C_01_16 { get; set; }
        public Nullable<decimal> C_01_17 { get; set; }
        public Nullable<decimal> C_01_18 { get; set; }
        public Nullable<decimal> C_01_19 { get; set; }
        public Nullable<decimal> C_01_30 { get; set; }
        public Nullable<decimal> C_01_31 { get; set; }
        public Nullable<decimal> C_01_41 { get; set; }
        public Nullable<decimal> C_01_32 { get; set; }
        public Nullable<decimal> C_01_42 { get; set; }
        public Nullable<decimal> C_01_43 { get; set; }
        public Nullable<decimal> C_01_33 { get; set; }
        public Nullable<decimal> C_01_40 { get; set; }
        public Nullable<decimal> C_01_50 { get; set; }
        public Nullable<decimal> C_01_60 { get; set; }
        public Nullable<decimal> C_01_70 { get; set; }
        public Nullable<decimal> C_01_71 { get; set; }
        public Nullable<decimal> C_01_80 { get; set; }
        public Nullable<decimal> C_01_81 { get; set; }
        public Nullable<decimal> C_01_82 { get; set; }
        public string CH_RA { get; set; }
    }
}
