//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCACC
    {
        public DOCACC()
        {
            this.DOCACCSTORE = new HashSet<DOCACCSTORE>();
        }
    
        public string NODOC { get; set; }
        public string TYPDOC { get; set; }
        public short POS { get; set; }
        public string OBKOD { get; set; }
        public string STKOD { get; set; }
        public string STIME { get; set; }
        public string M_KA { get; set; }
        public Nullable<decimal> K_VO { get; set; }
        public Nullable<decimal> CENA { get; set; }
        public Nullable<decimal> OTSTAPKA { get; set; }
        public Nullable<decimal> VID_PRICHOD { get; set; }
        public Nullable<decimal> DDS { get; set; }
        public Nullable<int> CODE { get; set; }
        public string OBKOD2 { get; set; }
    
        public virtual DOC DOC { get; set; }
        public virtual ICollection<DOCACCSTORE> DOCACCSTORE { get; set; }
    }
}
