//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAR_KARTA
    {
        public int NOM_GAR_KARTA { get; set; }
        public string NODOC { get; set; }
        public string TYPDOC { get; set; }
        public string STKOD { get; set; }
        public Nullable<short> POS { get; set; }
        public string FABNOM { get; set; }
        public string DVIGATEL { get; set; }
        public string NOM_DVIGATEL { get; set; }
        public Nullable<int> ID_SERVISE { get; set; }
        public Nullable<decimal> MESECI { get; set; }
    }
}
