//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_BOOK
    {
        public string INV_NO { get; set; }
        public string FABR_NO { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public string NAME { get; set; }
        public string VID_DA { get; set; }
        public string OTCET_UNIT { get; set; }
        public string MOL { get; set; }
        public string PREDNAZ_DA { get; set; }
        public Nullable<System.DateTime> DATE_ZAPRH { get; set; }
        public string IS_PROBEG { get; set; }
        public Nullable<decimal> BEGIN_STOJNOST { get; set; }
        public Nullable<decimal> BEGIN_AMORTIZACIA { get; set; }
        public Nullable<decimal> SROK_GODNOST { get; set; }
        public Nullable<decimal> KOEF_AMORT { get; set; }
        public string IS_OTCISL { get; set; }
        public Nullable<System.DateTime> DATE_OTCISL { get; set; }
    }
}
