//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IZDELIE_ITEM
    {
        public string IZD_CODE { get; set; }
        public string P_K { get; set; }
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public Nullable<decimal> RAZH_NORM { get; set; }
        public string IS_ISLEME { get; set; }
        public Nullable<decimal> ID { get; set; }
        public string CODE { get; set; }
        public string CEH { get; set; }
    }
}
