//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA
    {
        public KASA()
        {
            this.KASA_ITEM = new HashSet<KASA_ITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<System.DateTime> BYDATE { get; set; }
        public string TXT { get; set; }
        public string NODOC { get; set; }
        public string TYPDOC { get; set; }
        public Nullable<short> USR { get; set; }
    
        public virtual ICollection<KASA_ITEM> KASA_ITEM { get; set; }
    }
}
