//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_DOC
    {
        public KASA_DOC()
        {
            this.KASA_DOCACC = new HashSet<KASA_DOCACC>();
        }
    
        public string NODOC { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<int> KOD_OPR { get; set; }
        public Nullable<System.DateTime> DATADOC { get; set; }
        public string NOMDOC { get; set; }
        public string TEXTDOC { get; set; }
        public Nullable<short> DDS_CODE { get; set; }
        public Nullable<short> DDS_PREDMET_CODE { get; set; }
        public string B_N { get; set; }
        public Nullable<decimal> PRCNT_DDS { get; set; }
        public string KLIENT_NAME { get; set; }
        public string DAN_NO { get; set; }
        public Nullable<short> KLON { get; set; }
        public Nullable<decimal> SUMA { get; set; }
        public Nullable<decimal> SUMA_VAL { get; set; }
        public Nullable<decimal> SUMA_KOL { get; set; }
    
        public virtual ICollection<KASA_DOCACC> KASA_DOCACC { get; set; }
    }
}
