//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_ITEM
    {
        public int ID { get; set; }
        public short POS { get; set; }
        public string DIG_CODE { get; set; }
        public Nullable<decimal> ST_VAL { get; set; }
        public Nullable<decimal> KURS { get; set; }
        public Nullable<short> VID { get; set; }
        public string NOTES { get; set; }
    
        public virtual KASA KASA { get; set; }
    }
}
