//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPR
    {
        public OPR()
        {
            this.OPRITEM = new HashSet<OPRITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> STORNO_ID { get; set; }
        public string NOM_DOC { get; set; }
        public Nullable<System.DateTime> DATE_DOC { get; set; }
        public string TYPE_DOC { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
        public string ENTER_USR_CODE { get; set; }
        public Nullable<System.DateTime> ACC_DATE { get; set; }
        public string ACC_USR_CODE { get; set; }
        public Nullable<int> PAPKA { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> VALEUR { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> NOM_PAPKA { get; set; }
        public Nullable<decimal> SEQ { get; set; }
    
        public virtual ICollection<OPRITEM> OPRITEM { get; set; }
    }
}
