//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public ORDERS()
        {
            this.ORDERS_ITEM = new HashSet<ORDERS_ITEM>();
        }
    
        public int NOM_ORDER { get; set; }
        public Nullable<System.DateTime> DATE_ORDER { get; set; }
        public string FAX_NOM { get; set; }
    
        public virtual ICollection<ORDERS_ITEM> ORDERS_ITEM { get; set; }
    }
}
