//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREKLU
    {
        public decimal ID { get; set; }
        public decimal OPR { get; set; }
        public string NAME { get; set; }
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public string D_K { get; set; }
        public string SMETKA2 { get; set; }
        public string PARTIDA2 { get; set; }
        public string D_K2 { get; set; }
    }
}
