//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAZH
    {
        public string NOM_DOC { get; set; }
        public string NODOC2 { get; set; }
        public Nullable<System.DateTime> DATE_DOC { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> SUMA { get; set; }
        public Nullable<decimal> DDSSUMA { get; set; }
        public Nullable<int> KOD { get; set; }
        public string DANNO { get; set; }
        public string IME { get; set; }
        public Nullable<short> PAPKA { get; set; }
        public Nullable<decimal> NOM_PAPKA { get; set; }
    }
}
