//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_USER
    {
        public REG_USER()
        {
            this.ITEM_DOC_RIGHTS = new HashSet<ITEM_DOC_RIGHTS>();
            this.ITEM_KLI_RIGHTS = new HashSet<ITEM_KLI_RIGHTS>();
            this.ITEM_RIGHTS = new HashSet<ITEM_RIGHTS>();
        }
    
        public string NAME { get; set; }
        public string PASS { get; set; }
        public Nullable<short> ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ALL_KLI { get; set; }
        public string ALL_DOC { get; set; }
        public string ALL_EDIT_PRICE { get; set; }
        public string ALL_EDIT_OLD_DOC { get; set; }
        public string ALL_NAL_SKLAD { get; set; }
        public string ALL_KONT_DOST { get; set; }
        public string ALL_CBX_DELETE { get; set; }
        public string ALL_VIEW_DOST_CENI { get; set; }
        public string ALL_CBX_F2 { get; set; }
        public string ALL_UPDATE_KONT_FAKT { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public string POSITION { get; set; }
    
        public virtual ICollection<ITEM_DOC_RIGHTS> ITEM_DOC_RIGHTS { get; set; }
        public virtual ICollection<ITEM_KLI_RIGHTS> ITEM_KLI_RIGHTS { get; set; }
        public virtual ICollection<ITEM_RIGHTS> ITEM_RIGHTS { get; set; }
    }
}
