//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDA
    {
        public string SMETKA { get; set; }
        public string PARTIDA { get; set; }
        public System.DateTime BYDATE { get; set; }
        public Nullable<decimal> PERIOD_DT_OB { get; set; }
        public Nullable<decimal> PERIOD_KT_OB { get; set; }
        public Nullable<decimal> DT_OB { get; set; }
        public Nullable<decimal> KT_OB { get; set; }
        public Nullable<decimal> DT_SALDO { get; set; }
        public Nullable<decimal> KT_SALDO { get; set; }
        public Nullable<decimal> PERIOD_DT_OB_VAL { get; set; }
        public Nullable<decimal> PERIOD_KT_OB_VAL { get; set; }
        public Nullable<decimal> DT_OB_VAL { get; set; }
        public Nullable<decimal> KT_OB_VAL { get; set; }
        public Nullable<decimal> DT_SALDO_VAL { get; set; }
        public Nullable<decimal> KT_SALDO_VAL { get; set; }
        public Nullable<decimal> PERIOD_DT_OB_KOL { get; set; }
        public Nullable<decimal> PERIOD_KT_OB_KOL { get; set; }
        public Nullable<decimal> DT_OB_KOL { get; set; }
        public Nullable<decimal> KT_OB_KOL { get; set; }
        public Nullable<decimal> DT_SALDO_KOL { get; set; }
        public Nullable<decimal> KT_SALDO_KOL { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
    }
}
