//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDNEVNIK_DDS
    {
        public int ID { get; set; }
        public short POS { get; set; }
        public Nullable<short> DDS_CODE { get; set; }
        public Nullable<short> DDS_PREDMET_CODE { get; set; }
        public string B_N { get; set; }
        public Nullable<decimal> PRCNT_DDS { get; set; }
        public Nullable<decimal> DDS_SUM { get; set; }
        public string KLIENT_NAME { get; set; }
        public string DAN_NO { get; set; }
        public Nullable<short> KLON { get; set; }
    }
}
