//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOC_CU
    {
        public string NODOC { get; set; }
        public string NODOC2 { get; set; }
        public string TYPDOC { get; set; }
        public string NOREFDOC { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<System.DateTime> DATADOC { get; set; }
        public string TEXTDOC { get; set; }
        public Nullable<decimal> OTSTPKA { get; set; }
        public Nullable<short> OBKOD { get; set; }
        public string OBIME { get; set; }
        public string OBADR { get; set; }
        public string OBDANNO { get; set; }
        public string OBBULSTAT { get; set; }
        public string OBMOL { get; set; }
        public string OBMOLPOL { get; set; }
        public string OBMOLLP { get; set; }
        public string OBMOLPALNOM { get; set; }
        public Nullable<System.DateTime> DATAPOL { get; set; }
        public Nullable<short> VIDPL { get; set; }
        public string VIDPLTEXT { get; set; }
        public string DSMOL { get; set; }
        public string DSPREDAL { get; set; }
        public string DIG_CODE { get; set; }
        public string OBTYP { get; set; }
        public string BANKSMETKA { get; set; }
        public Nullable<decimal> SUMA { get; set; }
        public Nullable<decimal> SUMA_OTSTAPKA { get; set; }
        public Nullable<decimal> DDS { get; set; }
        public Nullable<decimal> DDSSUMA { get; set; }
        public Nullable<short> DDS_CODE { get; set; }
        public Nullable<short> DDS_PREDMET_CODE { get; set; }
        public string USR_CRT { get; set; }
        public string USR_CHG { get; set; }
        public Nullable<short> SKLNO { get; set; }
        public Nullable<System.DateTime> DATAPADEJ { get; set; }
        public Nullable<decimal> KASA_OPR_ID { get; set; }
        public Nullable<System.DateTime> TIME_CRT { get; set; }
        public Nullable<System.DateTime> TIME_CHG { get; set; }
        public string IS_PRINT { get; set; }
    }
}
