//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPART_POL
    {
        public int CODE { get; set; }
        public string PARTNUMBER { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_BG { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string VAL_DIG_CODE { get; set; }
        public Nullable<decimal> MIN_KOL { get; set; }
        public Nullable<decimal> POR_KOL { get; set; }
        public Nullable<decimal> POSLEDNA_POKUP_CENA { get; set; }
        public string CUST_CODE { get; set; }
        public Nullable<decimal> MITO { get; set; }
        public string M_KA { get; set; }
        public Nullable<decimal> PECHALBA { get; set; }
        public Nullable<decimal> DDS { get; set; }
        public Nullable<decimal> SIZE1 { get; set; }
        public Nullable<decimal> SIZE2 { get; set; }
        public string COLOUR { get; set; }
        public Nullable<int> FBOBEKT { get; set; }
        public string FBPARTNO { get; set; }
        public string IS_ACTIV { get; set; }
        public Nullable<decimal> PRICE_MONTAG { get; set; }
        public string SCANCODE { get; set; }
        public string NAME2 { get; set; }
        public string NAME1 { get; set; }
        public string IS_VISIBLE { get; set; }
        public Nullable<short> CATEGORY { get; set; }
        public string EUROCODE { get; set; }
        public Nullable<System.DateTime> ORDKOL_TS { get; set; }
        public Nullable<System.DateTime> DOST_TS { get; set; }
        public string TXT { get; set; }
        public string HARMOD { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string IS_PART { get; set; }
        public string PARTNUMBER2 { get; set; }
        public Nullable<int> OWNER_ID { get; set; }
        public string MOREINFO { get; set; }
    }
}
