//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIES_DDS_SEC_05
    {
        public string USER_NAME { get; set; }
        public string OTCP { get; set; }
        public string SEC_05_CODE { get; set; }
        public short SEC_05_NRED { get; set; }
        public string SEC_05_VIN { get; set; }
        public Nullable<decimal> SEC_05_DOO { get; set; }
        public Nullable<decimal> SEC_05_DOTS { get; set; }
        public Nullable<decimal> SEC_05_DOUS { get; set; }
        public string SEC_05_OTCP { get; set; }
    }
}
