//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNOSINVOICE
    {
        public string VNOSKOD { get; set; }
        public string NODOC { get; set; }
        public Nullable<System.DateTime> DATADOC { get; set; }
        public string DIG_CODE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual VNOS VNOS { get; set; }
    }
}
