//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridExample.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAPRH_IZDELIE
    {
        public ZAPRH_IZDELIE()
        {
            this.ZAPRH_IZDELIE_ITEM = new HashSet<ZAPRH_IZDELIE_ITEM>();
        }
    
        public System.DateTime BYDATE { get; set; }
        public string SKLAD { get; set; }
        public string TOSKLAD { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> KOL { get; set; }
        public string FROM_ISLEME { get; set; }
        public Nullable<int> OPR_ID { get; set; }
    
        public virtual ICollection<ZAPRH_IZDELIE_ITEM> ZAPRH_IZDELIE_ITEM { get; set; }
    }
}
