//------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.AuthenticationHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.CacheControlHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.ContentDispositionHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.ContentRangeHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.EntityTagHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.MediaTypeHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.NameValueHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.NameValueWithParametersHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.ProductHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.ProductInfoHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.RangeHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope="member", Target="System.Net.Http.Headers.RangeConditionHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.RangeItemHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.RetryConditionHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.StringWithQualityHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.TransferCodingHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.ViaHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "System.Net.Http.Headers.WarningHeaderValue.#System.ICloneable.Clone()", Justification = "code is clone of System.Net.Http")]
