//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ApplicationServer.Http {
    
    
    internal partial class StringResources {
        
        static System.Resources.ResourceManager resourceManager;
        
        static System.Globalization.CultureInfo resourceCulture;
        
        private StringResources() {
        }
        
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceManager, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.ApplicationServer.Http.StringResources", typeof(StringResources).Assembly);
                    resourceManager = temp;
                }
                return resourceManager;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("StrictResXFileCodeGenerator", "4.0.0.0")]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contoso-stop-at-root-element-xmlns.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contoso_stop_at_root_element_xmlns_xml {
            get {
                return ResourceManager.GetString("contoso_stop_at_root_element_xmlns_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contoso-stop-at-root-element.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contoso_stop_at_root_element_xml {
            get {
                return ResourceManager.GetString("contoso_stop_at_root_element_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-author.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_author_json {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_author_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-author.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_author_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_author_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-end.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_end_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_end_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-genre-value.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_genre_value_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_genre_value_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-genre.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_genre_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_genre_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-isbn.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_ISBN_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_ISBN_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-title-text.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_title_text_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_title_text_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-title.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_title_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_title_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_xml {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-genre-value.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_genre_value_json {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_genre_value_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-genres-enum.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_genres_enum_json {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_genres_enum_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-isbn-value.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_ISBN_value_json {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_ISBN_value_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-isbn.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_ISBN_json {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_ISBN_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_json {
            get {
                return ResourceManager.GetString("contosoBooks_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_xml {
            get {
                return ResourceManager.GetString("contosoBooks_xml", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks.xsd;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_xsd {
            get {
                return ResourceManager.GetString("contosoBooks_xsd", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-full.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_full_txt {
            get {
                return ResourceManager.GetString("headers_full_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-stop-at-accept.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_stop_at_accept_txt {
            get {
                return ResourceManager.GetString("headers_stop_at_accept_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-stop-at-accept-value.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_stop_at_accept_value_txt {
            get {
                return ResourceManager.GetString("headers_stop_at_accept_value_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-stop-at-contenttype.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_stop_at_contenttype_txt {
            get {
                return ResourceManager.GetString("headers_stop_at_contenttype_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-stop-at-contenttype-value.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_stop_at_contenttype_value_txt {
            get {
                return ResourceManager.GetString("headers_stop_at_contenttype_value_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-unformatted.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_unformatted_json {
            get {
                return ResourceManager.GetString("contosoBooks_unformatted_json", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\headers-full-unformatted.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string headers_full_unformatted_txt {
            get {
                return ResourceManager.GetString("headers_full_unformatted_txt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: microsoft\applicationserver\http\testclient\testdata\contosobooks-stop-at-book-publicationdate-value.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</summary>
        internal static string contosoBooks_stop_at_book_publicationdate_value {
            get {
                return ResourceManager.GetString("contosoBooks_stop_at_book_publicationdate_value", Culture);
            }
        }
    }
}

