//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Extras = new HashSet<Extra>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProducerID { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual ICollection<Extra> Extras { get; set; }
    }
}
