// <copyright file="GlobalSuppressions.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.ProjectTemplateWizard#RunFinished()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.WizardCommand#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#OnPropertyChanged`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#SetValue`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ScenarioModel.#.ctor(Microsoft.ServiceModel.Interop.ConfigurationWizard.Configuration.interoperabilityWizardScenario,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.PageViewModelBase>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ScenarioPageViewModel.#.ctor(System.Collections.Generic.IEnumerable`1<Microsoft.ServiceModel.Interop.ConfigurationWizard.Configuration.interoperabilityWizardScenario>,System.Action`1<System.Collections.Generic.IEnumerable`1<Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.PageViewModelBase>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.ProjectTemplateWizard.#RunFinished()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.WizardCommand.#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#SetValue`1(!!0&,!!0,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#SetValue`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", MessageId = "System.String.Equals(System.String,System.StringComparison)", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.ProjectTemplateWizard.#ProjectItemFinishedGenerating(EnvDTE.ProjectItem)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", MessageId = "System.String.EndsWith(System.String,System.StringComparison)", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.WizardCommand.#AnyReference(VSLangProj.VSProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", MessageId = "System.String.Equals(System.String,System.StringComparison)", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils.WizardCommand.#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", MessageId = "System.String.StartsWith(System.String,System.Boolean,System.Globalization.CultureInfo)", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.Services.T4Invoker.#TransformText(System.String,System.String,System.Collections.Generic.IDictionary`2<System.String,System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Utils")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Utils", Scope = "namespace", Target = "Microsoft.ServiceModel.Interop.ExtensionUtils")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Expresion", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#OnPropertyChanged`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Expresion", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#SetValue`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.Services.ConfigurationModelLoader.#Load()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.ViewModel.ObservableModel.#SetValue`1(!!0&,!!0,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.Services.TemplateService.#WriteBindingToFile(System.String,System.String,System.String,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.Services.ICertificateStoreService.#GetStoreLocations()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.ServiceModel.Interop.ConfigurationWizard.Services.ICertificateStoreService.#GetStores()")]
