//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http.Formatting.OData {
    
    
    internal partial class BaselineResource {
        
        static System.Resources.ResourceManager resourceManager;
        
        static System.Globalization.CultureInfo resourceCulture;
        
        private BaselineResource() {
        }
        
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceManager, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("System.Net.Http.Formatting.OData.BaselineResource", typeof(BaselineResource).Assembly);
                    resourceManager = temp;
                }
                return resourceManager;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("StrictResXFileCodeGenerator", "4.0.0.0")]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:anyURI xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">http://www.tempuri.org:8000/AbsoluteUri</d:anyURI></summary>
        internal static string AbsoluteUri {
            get {
                return ResourceManager.GetString("AbsoluteUri", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:boolean xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Boolean">true</d:boolean></summary>
        internal static string Bool {
            get {
                return ResourceManager.GetString("Bool", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:unsignedByte xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Byte">64</d:unsignedByte></summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:base64Binary xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Binary">AAIgQID/</d:base64Binary></summary>
        internal static string ByteArray {
            get {
                return ResourceManager.GetString("ByteArray", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:char xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">A</d:char></summary>
        internal static string Char {
            get {
                return ResourceManager.GetString("Char", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:dateTime xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.DateTime">2010-01-01T00:00:00</d:dateTime></summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:decimal xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Decimal">12345.99999</d:decimal></summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:double xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Double">99999.12345</d:double></summary>
        internal static string Double {
            get {
                return ResourceManager.GetString("Double", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:guid xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Guid">f99080c0-2f9e-472e-8c72-1a8ecd9f902d</d:guid></summary>
        internal static string Guid {
            get {
                return ResourceManager.GetString("Guid", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:short xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Int16">-32768</d:short></summary>
        internal static string Int16 {
            get {
                return ResourceManager.GetString("Int16", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:int xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Int32">-2147483648</d:int></summary>
        internal static string Int32 {
            get {
                return ResourceManager.GetString("Int32", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:long xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Int64">-9223372036854775808</d:long></summary>
        internal static string Int64 {
            get {
                return ResourceManager.GetString("Int64", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:boolean xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Boolean">false</d:boolean></summary>
        internal static string NullableBool {
            get {
                return ResourceManager.GetString("NullableBool", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:int xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:null="true" /></summary>
        internal static string NullableInt {
            get {
                return ResourceManager.GetString("NullableInt", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:anyType xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"></d:anyType></summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:anyURI xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">RelativeUri</d:anyURI></summary>
        internal static string RelativeUri {
            get {
                return ResourceManager.GetString("RelativeUri", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:byte xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.SByte">-128</d:byte></summary>
        internal static string SByte {
            get {
                return ResourceManager.GetString("SByte", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:float xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="Edm.Single">INF</d:float></summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:string xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">This is a Test String</d:string></summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfboolean xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element m:type="Edm.Boolean" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">true</element>
        ///  <element m:type="Edm.Boolean" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">false</element>
        ///  <element m:type="Edm.Boolean" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">true</element>
        ///  <element m:type="Edm.Boolean" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">false</element>
        ///</ArrayOfboolean></summary>
        internal static string TestArrayOfBools {
            get {
                return ResourceManager.GetString("TestArrayOfBools", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfint xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">10</element>
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">20</element>
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">30</element>
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">40</element>
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">50</element>
        ///</ArrayOfint></summary>
        internal static string TestArrayOfInts {
            get {
                return ResourceManager.GetString("TestArrayOfInts", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfanyType xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element m:type="Edm.Int32" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">1</element>
        ///  <element>Frank</element>
        ///  <element m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Age m:type="Edm.Int32">22</Age>
        ///    <FavoriteHobby m:type="HobbyActivity">
        ///      <ActivityName>Xbox Gaming</ActivityName>
        ///    </FavoriteHobby>
        ///    <FirstName>Tom</FirstName>
        ///    <Gender>Male</Gender>
        ///    <HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///      <City>Redmond</City>
        ///      <State>WA</State>
        ///      <StreetAddress>4852 158th Ave NE</StreetAddress>
        ///      <ZipCode m:type="Edm.Int32">98054</ZipCode>
        ///    </HomeAddress>
        ///    <HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///      <AreaCode m:type="Edm.Int32">425</AreaCode>
        ///      <CountryCode m:type="Edm.Int32">1</CountryCode>
        ///      <Number m:type="Edm.Int32">9879091</Number>
        ///      <PhoneType>HomePhone</PhoneType>
        ///    </HomeNumber>
        ///    <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///      <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias2</d:element>
        ///    </OtherNames>
        ///  </element>
        ///  <element m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Age m:type="Edm.Int32">23</Age>
        ///    <FavoriteHobby m:type="HobbyActivity">
        ///      <ActivityName>Xbox Gaming</ActivityName>
        ///    </FavoriteHobby>
        ///    <FirstName>Chandler</FirstName>
        ///    <Gender>Male</Gender>
        ///    <HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///      <City>Redmond</City>
        ///      <State>WA</State>
        ///      <StreetAddress>4853 159th Ave NE</StreetAddress>
        ///      <ZipCode m:type="Edm.Int32">98055</ZipCode>
        ///    </HomeAddress>
        ///    <HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///      <AreaCode m:type="Edm.Int32">425</AreaCode>
        ///      <CountryCode m:type="Edm.Int32">1</CountryCode>
        ///      <Number m:type="Edm.Int32">9879092</Number>
        ///      <PhoneType>HomePhone</PhoneType>
        ///    </HomeNumber>
        ///    <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///      <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias3</d:element>
        ///    </OtherNames>
        ///    <CurrentWorkItem m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem">
        ///      <EmployeeID m:type="Edm.Int32">3</EmployeeID>
        ///      <IsCompleted m:type="Edm.Boolean">false</IsCompleted>
        ///      <NumberOfHours m:type="Edm.Single">19</NumberOfHours>
        ///      <WorkItemID m:type="Edm.Int32">28</WorkItemID>
        ///    </CurrentWorkItem>
        ///    <DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///    <EmployeeId m:type="Edm.Int64">3</EmployeeId>
        ///    <Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///      <Age m:type="Edm.Int32">24</Age>
        ///      <FirstName>Ross</FirstName>
        ///      <Gender>Male</Gender>
        ///      <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///        <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias4</d:element>
        ///      </OtherNames>
        ///      <DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///      <EmployeeId m:type="Edm.Int64">4</EmployeeId>
        ///    </Manager>
        ///  </element>
        ///</ArrayOfanyType></summary>
        internal static string TestCollectionOfObjects {
            get {
                return ResourceManager.GetString("TestCollectionOfObjects", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfPerson xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Age m:type="Edm.Int32">20</Age>
        ///    <FavoriteHobby m:type="HobbyActivity">
        ///      <ActivityName>Xbox Gaming</ActivityName>
        ///    </FavoriteHobby>
        ///    <FirstName>Frank</FirstName>
        ///    <Gender>Male</Gender>
        ///    <HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///      <City>Redmond</City>
        ///      <State>WA</State>
        ///      <StreetAddress>4850 156th Ave NE</StreetAddress>
        ///      <ZipCode m:type="Edm.Int32">98052</ZipCode>
        ///    </HomeAddress>
        ///    <HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///      <AreaCode m:type="Edm.Int32">425</AreaCode>
        ///      <CountryCode m:type="Edm.Int32">1</CountryCode>
        ///      <Number m:type="Edm.Int32">9879089</Number>
        ///      <PhoneType>HomePhone</PhoneType>
        ///    </HomeNumber>
        ///    <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///      <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias0</d:element>
        ///    </OtherNames>
        ///  </element>
        ///  <element m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Age m:type="Edm.Int32">21</Age>
        ///    <FavoriteHobby m:type="HobbyActivity">
        ///      <ActivityName>Xbox Gaming</ActivityName>
        ///    </FavoriteHobby>
        ///    <FirstName>Steve</FirstName>
        ///    <Gender>Male</Gender>
        ///    <HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///      <City>Redmond</City>
        ///      <State>WA</State>
        ///      <StreetAddress>4851 157th Ave NE</StreetAddress>
        ///      <ZipCode m:type="Edm.Int32">98053</ZipCode>
        ///    </HomeAddress>
        ///    <HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///      <AreaCode m:type="Edm.Int32">425</AreaCode>
        ///      <CountryCode m:type="Edm.Int32">1</CountryCode>
        ///      <Number m:type="Edm.Int32">9879090</Number>
        ///      <PhoneType>HomePhone</PhoneType>
        ///    </HomeNumber>
        ///    <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///      <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias1</d:element>
        ///    </OtherNames>
        ///  </element>
        ///  <element m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Age m:type="Edm.Int32">22</Age>
        ///    <FavoriteHobby m:type="HobbyActivity">
        ///      <ActivityName>Xbox Gaming</ActivityName>
        ///    </FavoriteHobby>
        ///    <FirstName>Tom</FirstName>
        ///    <Gender>Male</Gender>
        ///    <HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///      <City>Redmond</City>
        ///      <State>WA</State>
        ///      <StreetAddress>4852 158th Ave NE</StreetAddress>
        ///      <ZipCode m:type="Edm.Int32">98054</ZipCode>
        ///    </HomeAddress>
        ///    <HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///      <AreaCode m:type="Edm.Int32">425</AreaCode>
        ///      <CountryCode m:type="Edm.Int32">1</CountryCode>
        ///      <Number m:type="Edm.Int32">9879091</Number>
        ///      <PhoneType>HomePhone</PhoneType>
        ///    </HomeNumber>
        ///    <OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///      <d:element xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">Alias2</d:element>
        ///    </OtherNames>
        ///  </element>
        ///</ArrayOfPerson></summary>
        internal static string TestCollectionOfPerson {
            get {
                return ResourceManager.GetString("TestCollectionOfPerson", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:Person xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Person">
        ///  <d:Age m:type="Edm.Int32">20</d:Age>
        ///  <d:FavoriteHobby m:type="HobbyActivity">
        ///    <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///  </d:FavoriteHobby>
        ///  <d:FirstName>Frank</d:FirstName>
        ///  <d:Gender>Male</d:Gender>
        ///  <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///    <d:City>Redmond</d:City>
        ///    <d:State>WA</d:State>
        ///    <d:StreetAddress>4850 156th Ave NE</d:StreetAddress>
        ///    <d:ZipCode m:type="Edm.Int32">98052</d:ZipCode>
        ///  </d:HomeAddress>
        ///  <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///    <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///    <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///    <d:Number m:type="Edm.Int32">9879089</d:Number>
        ///    <d:PhoneType>HomePhone</d:PhoneType>
        ///  </d:HomeNumber>
        ///  <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///    <d:element>Alias0</d:element>
        ///  </d:OtherNames>
        ///</d:Person></summary>
        internal static string TestComplexTypePerson {
            get {
                return ResourceManager.GetString("TestComplexTypePerson", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfKeyValueOfintstring xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element m:type="http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Key m:type="Edm.Int32">1</Key>
        ///    <Value>Frank</Value>
        ///  </element>
        ///  <element m:type="http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Key m:type="Edm.Int32">2</Key>
        ///    <Value>Steve</Value>
        ///  </element>
        ///  <element m:type="http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Key m:type="Edm.Int32">3</Key>
        ///    <Value>Tom</Value>
        ///  </element>
        ///  <element m:type="http://schemas.microsoft.com/2003/10/Serialization/Arrays/KeyValueOfintstring" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        ///    <Key m:type="Edm.Int32">4</Key>
        ///    <Value>Chandler</Value>
        ///  </element>
        ///</ArrayOfKeyValueOfintstring></summary>
        internal static string TestDictionary {
            get {
                return ResourceManager.GetString("TestDictionary", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<entry xml:base="http://www.tempuri.org/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
        ///  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" type="application/atom+xml;type=entry" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)/CurrentWorkItem">
        ///    <m:inline>
        ///      <entry>
        ///        <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)</id>
        ///        <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///        <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)" />
        ///        <title />
        ///        <updated>UpdatedTime</updated>
        ///        <author>
        ///          <name />
        ///        </author>
        ///        <content type="application/xml">
        ///          <m:properties>
        ///            <d:EmployeeID m:type="Edm.Int32">0</d:EmployeeID>
        ///            <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///            <d:NumberOfHours m:type="Edm.Single">16</d:NumberOfHours>
        ///            <d:WorkItemID m:type="Edm.Int32">25</d:WorkItemID>
        ///          </m:properties>
        ///        </content>
        ///      </entry>
        ///    </m:inline>
        ///  </link>
        ///  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" type="application/atom+xml;type=feed" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)/DirectReports">
        ///    <m:inline>
        ///      <feed>
        ///        <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee</id>
        ///        <title />
        ///        <updated>UpdatedTime</updated>
        ///        <author>
        ///          <name />
        ///        </author>
        ///      </feed>
        ///    </m:inline>
        ///  </link>
        ///  <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)</id>
        ///  <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///  <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)" />
        ///  <title />
        ///  <updated>UpdatedTime</updated>
        ///  <author>
        ///    <name />
        ///  </author>
        ///  <content type="application/xml">
        ///    <m:properties>
        ///      <d:Age m:type="Edm.Int32">20</d:Age>
        ///      <d:FavoriteHobby m:type="HobbyActivity">
        ///        <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///      </d:FavoriteHobby>
        ///      <d:FirstName>Frank</d:FirstName>
        ///      <d:Gender>Male</d:Gender>
        ///      <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///        <d:City>Redmond</d:City>
        ///        <d:State>WA</d:State>
        ///        <d:StreetAddress>4850 156th Ave NE</d:StreetAddress>
        ///        <d:ZipCode m:type="Edm.Int32">98052</d:ZipCode>
        ///      </d:HomeAddress>
        ///      <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///        <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///        <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///        <d:Number m:type="Edm.Int32">9879089</d:Number>
        ///        <d:PhoneType>HomePhone</d:PhoneType>
        ///      </d:HomeNumber>
        ///      <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///        <d:element>Alias0</d:element>
        ///      </d:OtherNames>
        ///      <d:EmployeeId m:type="Edm.Int64">0</d:EmployeeId>
        ///      <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///        <d:Age m:type="Edm.Int32">21</d:Age>
        ///        <d:FavoriteHobby m:type="HobbyActivity">
        ///          <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///        </d:FavoriteHobby>
        ///        <d:FirstName>Steve</d:FirstName>
        ///        <d:Gender>Male</d:Gender>
        ///        <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///          <d:City>Redmond</d:City>
        ///          <d:State>WA</d:State>
        ///          <d:StreetAddress>4851 157th Ave NE</d:StreetAddress>
        ///          <d:ZipCode m:type="Edm.Int32">98053</d:ZipCode>
        ///        </d:HomeAddress>
        ///        <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///          <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///          <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///          <d:Number m:type="Edm.Int32">9879090</d:Number>
        ///          <d:PhoneType>HomePhone</d:PhoneType>
        ///        </d:HomeNumber>
        ///        <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///          <d:element>Alias1</d:element>
        ///        </d:OtherNames>
        ///        <d:CurrentWorkItem m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem">
        ///          <d:EmployeeID m:type="Edm.Int32">1</d:EmployeeID>
        ///          <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///          <d:NumberOfHours m:type="Edm.Single">17</d:NumberOfHours>
        ///          <d:WorkItemID m:type="Edm.Int32">26</d:WorkItemID>
        ///        </d:CurrentWorkItem>
        ///        <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///        <d:EmployeeId m:type="Edm.Int64">1</d:EmployeeId>
        ///        <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///          <d:Age m:type="Edm.Int32">22</d:Age>
        ///          <d:FirstName>Tom</d:FirstName>
        ///          <d:Gender>Male</d:Gender>
        ///          <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///            <d:element>Alias2</d:element>
        ///          </d:OtherNames>
        ///          <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///          <d:EmployeeId m:type="Edm.Int64">2</d:EmployeeId>
        ///        </d:Manager>
        ///      </d:Manager>
        ///    </m:properties>
        ///  </content>
        ///</entry></summary>
        internal static string TestEntityTypeBasic {
            get {
                return ResourceManager.GetString("TestEntityTypeBasic", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<entry xml:base="http://www.tempuri.org/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
        ///  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" type="application/atom+xml;type=entry" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/MultipleKeyEmployee(EmployeeId=0,EmployeeGuid='844080c0-2f9e-472e-8c72-1a8ecd9f9037',UniqueStringId='Frank0')/CurrentWorkItem">
        ///    <m:inline>
        ///      <entry>
        ///        <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)</id>
        ///        <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///        <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)" />
        ///        <title />
        ///        <updated>UpdatedTime</updated>
        ///        <author>
        ///          <name />
        ///        </author>
        ///        <content type="application/xml">
        ///          <m:properties>
        ///            <d:EmployeeID m:type="Edm.Int32">0</d:EmployeeID>
        ///            <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///            <d:NumberOfHours m:type="Edm.Single">16</d:NumberOfHours>
        ///            <d:WorkItemID m:type="Edm.Int32">25</d:WorkItemID>
        ///          </m:properties>
        ///        </content>
        ///      </entry>
        ///    </m:inline>
        ///  </link>
        ///  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" type="application/atom+xml;type=feed" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/MultipleKeyEmployee(EmployeeId=0,EmployeeGuid='844080c0-2f9e-472e-8c72-1a8ecd9f9037',UniqueStringId='Frank0')/DirectReports">
        ///    <m:inline>
        ///      <feed>
        ///        <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee</id>
        ///        <title />
        ///        <updated>UpdatedTime</updated>
        ///        <author>
        ///          <name />
        ///        </author>
        ///      </feed>
        ///    </m:inline>
        ///  </link>
        ///  <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/MultipleKeyEmployee(EmployeeId=0,EmployeeGuid='844080c0-2f9e-472e-8c72-1a8ecd9f9037',UniqueStringId='Frank0')</id>
        ///  <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/MultipleKeyEmployee" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///  <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/MultipleKeyEmployee(EmployeeId=0,EmployeeGuid='844080c0-2f9e-472e-8c72-1a8ecd9f9037',UniqueStringId='Frank0')" />
        ///  <title />
        ///  <updated>UpdatedTime</updated>
        ///  <author>
        ///    <name />
        ///  </author>
        ///  <content type="application/xml">
        ///    <m:properties>
        ///      <d:Age m:type="Edm.Int32">20</d:Age>
        ///      <d:FavoriteHobby m:type="HobbyActivity">
        ///        <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///      </d:FavoriteHobby>
        ///      <d:FirstName>Frank</d:FirstName>
        ///      <d:Gender>Male</d:Gender>
        ///      <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///        <d:City>Redmond</d:City>
        ///        <d:State>WA</d:State>
        ///        <d:StreetAddress>4850 156th Ave NE</d:StreetAddress>
        ///        <d:ZipCode m:type="Edm.Int32">98052</d:ZipCode>
        ///      </d:HomeAddress>
        ///      <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///        <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///        <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///        <d:Number m:type="Edm.Int32">9879089</d:Number>
        ///        <d:PhoneType>HomePhone</d:PhoneType>
        ///      </d:HomeNumber>
        ///      <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///        <d:element>Alias0</d:element>
        ///      </d:OtherNames>
        ///      <d:EmployeeId m:type="Edm.Int64">0</d:EmployeeId>
        ///      <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///        <d:Age m:type="Edm.Int32">21</d:Age>
        ///        <d:FirstName>Steve</d:FirstName>
        ///        <d:Gender>Male</d:Gender>
        ///        <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///          <d:element>Alias1</d:element>
        ///        </d:OtherNames>
        ///        <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///        <d:EmployeeId m:type="Edm.Int64">1</d:EmployeeId>
        ///      </d:Manager>
        ///      <d:EmployeeGuid m:type="Edm.Guid">844080c0-2f9e-472e-8c72-1a8ecd9f9037</d:EmployeeGuid>
        ///      <d:UniqueStringId>Frank0</d:UniqueStringId>
        ///    </m:properties>
        ///  </content>
        ///</entry></summary>
        internal static string TestEntityTypeWithMultipleKeys {
            get {
                return ResourceManager.GetString("TestEntityTypeWithMultipleKeys", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<entry xml:base="http://www.tempuri.org/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
        ///  <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)</id>
        ///  <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///  <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)" />
        ///  <title />
        ///  <updated>UpdatedTime</updated>
        ///  <author>
        ///    <name />
        ///  </author>
        ///  <content type="application/xml">
        ///    <m:properties>
        ///      <d:EmployeeID m:type="Edm.Int32">0</d:EmployeeID>
        ///      <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///      <d:NumberOfHours m:type="Edm.Single">100</d:NumberOfHours>
        ///      <d:WorkItemID m:type="Edm.Int32">25</d:WorkItemID>
        ///    </m:properties>
        ///  </content>
        ///</entry></summary>
        internal static string TestEntityWorkItem {
            get {
                return ResourceManager.GetString("TestEntityWorkItem", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<entry xml:base="http://www.tempuri.org/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
        ///  <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/DerivedWorkItem(EmployeeID=0,WorkItemID=25)</id>
        ///  <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/DerivedWorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///  <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/DerivedWorkItem(EmployeeID=0,WorkItemID=25)" />
        ///  <title />
        ///  <updated>UpdatedTime</updated>
        ///  <author>
        ///    <name />
        ///  </author>
        ///  <content type="application/xml">
        ///    <m:properties>
        ///      <d:EmployeeID m:type="Edm.Int32">0</d:EmployeeID>
        ///      <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///      <d:NumberOfHours m:type="Edm.Single">100</d:NumberOfHours>
        ///      <d:WorkItemID m:type="Edm.Int32">25</d:WorkItemID>
        ///    </m:properties>
        ///  </content>
        ///</entry></summary>
        internal static string TestEntityWorkItemWithExplictKeys {
            get {
                return ResourceManager.GetString("TestEntityWorkItemWithExplictKeys", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<feed xml:base="http://www.tempuri.org/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
        ///  <entry>
        ///    <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" type="application/atom+xml;type=entry" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)/CurrentWorkItem">
        ///      <m:inline>
        ///        <entry>
        ///          <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)</id>
        ///          <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///          <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(25)" />
        ///          <title />
        ///          <updated>UpdatedTime</updated>
        ///          <author>
        ///            <name />
        ///          </author>
        ///          <content type="application/xml">
        ///            <m:properties>
        ///              <d:EmployeeID m:type="Edm.Int32">0</d:EmployeeID>
        ///              <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///              <d:NumberOfHours m:type="Edm.Single">16</d:NumberOfHours>
        ///              <d:WorkItemID m:type="Edm.Int32">25</d:WorkItemID>
        ///            </m:properties>
        ///          </content>
        ///        </entry>
        ///      </m:inline>
        ///    </link>
        ///    <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" type="application/atom+xml;type=feed" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)/DirectReports">
        ///      <m:inline>
        ///        <feed>
        ///          <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee</id>
        ///          <title />
        ///          <updated>UpdatedTime</updated>
        ///          <author>
        ///            <name />
        ///          </author>
        ///        </feed>
        ///      </m:inline>
        ///    </link>
        ///    <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)</id>
        ///    <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///    <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(0)" />
        ///    <title />
        ///    <updated>UpdatedTime</updated>
        ///    <author>
        ///      <name />
        ///    </author>
        ///    <content type="application/xml">
        ///      <m:properties>
        ///        <d:Age m:type="Edm.Int32">20</d:Age>
        ///        <d:FavoriteHobby m:type="HobbyActivity">
        ///          <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///        </d:FavoriteHobby>
        ///        <d:FirstName>Frank</d:FirstName>
        ///        <d:Gender>Male</d:Gender>
        ///        <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///          <d:City>Redmond</d:City>
        ///          <d:State>WA</d:State>
        ///          <d:StreetAddress>4850 156th Ave NE</d:StreetAddress>
        ///          <d:ZipCode m:type="Edm.Int32">98052</d:ZipCode>
        ///        </d:HomeAddress>
        ///        <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///          <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///          <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///          <d:Number m:type="Edm.Int32">9879089</d:Number>
        ///          <d:PhoneType>HomePhone</d:PhoneType>
        ///        </d:HomeNumber>
        ///        <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///          <d:element>Alias0</d:element>
        ///        </d:OtherNames>
        ///        <d:EmployeeId m:type="Edm.Int64">0</d:EmployeeId>
        ///        <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///          <d:Age m:type="Edm.Int32">21</d:Age>
        ///          <d:FavoriteHobby m:type="HobbyActivity">
        ///            <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///          </d:FavoriteHobby>
        ///          <d:FirstName>Steve</d:FirstName>
        ///          <d:Gender>Male</d:Gender>
        ///          <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///            <d:City>Redmond</d:City>
        ///            <d:State>WA</d:State>
        ///            <d:StreetAddress>4851 157th Ave NE</d:StreetAddress>
        ///            <d:ZipCode m:type="Edm.Int32">98053</d:ZipCode>
        ///          </d:HomeAddress>
        ///          <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///            <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///            <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///            <d:Number m:type="Edm.Int32">9879090</d:Number>
        ///            <d:PhoneType>HomePhone</d:PhoneType>
        ///          </d:HomeNumber>
        ///          <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///            <d:element>Alias1</d:element>
        ///          </d:OtherNames>
        ///          <d:CurrentWorkItem m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem">
        ///            <d:EmployeeID m:type="Edm.Int32">1</d:EmployeeID>
        ///            <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///            <d:NumberOfHours m:type="Edm.Single">17</d:NumberOfHours>
        ///            <d:WorkItemID m:type="Edm.Int32">26</d:WorkItemID>
        ///          </d:CurrentWorkItem>
        ///          <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///          <d:EmployeeId m:type="Edm.Int64">1</d:EmployeeId>
        ///          <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///            <d:Age m:type="Edm.Int32">22</d:Age>
        ///            <d:FirstName>Tom</d:FirstName>
        ///            <d:Gender>Male</d:Gender>
        ///            <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///              <d:element>Alias2</d:element>
        ///            </d:OtherNames>
        ///            <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///            <d:EmployeeId m:type="Edm.Int64">2</d:EmployeeId>
        ///          </d:Manager>
        ///        </d:Manager>
        ///      </m:properties>
        ///    </content>
        ///  </entry>
        ///  <entry>
        ///    <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" type="application/atom+xml;type=entry" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CurrentWorkItem" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(1)/CurrentWorkItem">
        ///      <m:inline>
        ///        <entry>
        ///          <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(26)</id>
        ///          <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///          <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem(26)" />
        ///          <title />
        ///          <updated>UpdatedTime</updated>
        ///          <author>
        ///            <name />
        ///          </author>
        ///          <content type="application/xml">
        ///            <m:properties>
        ///              <d:EmployeeID m:type="Edm.Int32">1</d:EmployeeID>
        ///              <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///              <d:NumberOfHours m:type="Edm.Single">17</d:NumberOfHours>
        ///              <d:WorkItemID m:type="Edm.Int32">26</d:WorkItemID>
        ///            </m:properties>
        ///          </content>
        ///        </entry>
        ///      </m:inline>
        ///    </link>
        ///    <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" type="application/atom+xml;type=feed" title="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DirectReports" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(1)/DirectReports">
        ///      <m:inline>
        ///        <feed>
        ///          <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee</id>
        ///          <title />
        ///          <updated>UpdatedTime</updated>
        ///          <author>
        ///            <name />
        ///          </author>
        ///        </feed>
        ///      </m:inline>
        ///    </link>
        ///    <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(1)</id>
        ///    <category term="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
        ///    <link rel="self" href="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee(1)" />
        ///    <title />
        ///    <updated>UpdatedTime</updated>
        ///    <author>
        ///      <name />
        ///    </author>
        ///    <content type="application/xml">
        ///      <m:properties>
        ///        <d:Age m:type="Edm.Int32">21</d:Age>
        ///        <d:FavoriteHobby m:type="HobbyActivity">
        ///          <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///        </d:FavoriteHobby>
        ///        <d:FirstName>Steve</d:FirstName>
        ///        <d:Gender>Male</d:Gender>
        ///        <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///          <d:City>Redmond</d:City>
        ///          <d:State>WA</d:State>
        ///          <d:StreetAddress>4851 157th Ave NE</d:StreetAddress>
        ///          <d:ZipCode m:type="Edm.Int32">98053</d:ZipCode>
        ///        </d:HomeAddress>
        ///        <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///          <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///          <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///          <d:Number m:type="Edm.Int32">9879090</d:Number>
        ///          <d:PhoneType>HomePhone</d:PhoneType>
        ///        </d:HomeNumber>
        ///        <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///          <d:element>Alias1</d:element>
        ///        </d:OtherNames>
        ///        <d:EmployeeId m:type="Edm.Int64">1</d:EmployeeId>
        ///        <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///          <d:Age m:type="Edm.Int32">22</d:Age>
        ///          <d:FavoriteHobby m:type="HobbyActivity">
        ///            <d:ActivityName>Xbox Gaming</d:ActivityName>
        ///          </d:FavoriteHobby>
        ///          <d:FirstName>Tom</d:FirstName>
        ///          <d:Gender>Male</d:Gender>
        ///          <d:HomeAddress m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/Address">
        ///            <d:City>Redmond</d:City>
        ///            <d:State>WA</d:State>
        ///            <d:StreetAddress>4852 158th Ave NE</d:StreetAddress>
        ///            <d:ZipCode m:type="Edm.Int32">98054</d:ZipCode>
        ///          </d:HomeAddress>
        ///          <d:HomeNumber m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.ComplexTypes/PhoneNumber">
        ///            <d:AreaCode m:type="Edm.Int32">425</d:AreaCode>
        ///            <d:CountryCode m:type="Edm.Int32">1</d:CountryCode>
        ///            <d:Number m:type="Edm.Int32">9879091</d:Number>
        ///            <d:PhoneType>HomePhone</d:PhoneType>
        ///          </d:HomeNumber>
        ///          <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///            <d:element>Alias2</d:element>
        ///          </d:OtherNames>
        ///          <d:CurrentWorkItem m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/WorkItem">
        ///            <d:EmployeeID m:type="Edm.Int32">2</d:EmployeeID>
        ///            <d:IsCompleted m:type="Edm.Boolean">false</d:IsCompleted>
        ///            <d:NumberOfHours m:type="Edm.Single">18</d:NumberOfHours>
        ///            <d:WorkItemID m:type="Edm.Int32">27</d:WorkItemID>
        ///          </d:CurrentWorkItem>
        ///          <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///          <d:EmployeeId m:type="Edm.Int64">2</d:EmployeeId>
        ///          <d:Manager m:type="http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee">
        ///            <d:Age m:type="Edm.Int32">23</d:Age>
        ///            <d:FirstName>Chandler</d:FirstName>
        ///            <d:Gender>Male</d:Gender>
        ///            <d:OtherNames m:type="MultiValue(http://schemas.microsoft.com/2003/10/Serialization/Arrays/ArrayOfstring)">
        ///              <d:element>Alias3</d:element>
        ///            </d:OtherNames>
        ///            <d:DirectReports m:type="MultiValue(http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/ArrayOfEmployee)" />
        ///            <d:EmployeeId m:type="Edm.Int64">3</d:EmployeeId>
        ///          </d:Manager>
        ///        </d:Manager>
        ///      </m:properties>
        ///    </content>
        ///  </entry>
        ///  <id>http://schemas.datacontract.org/2004/07/System.Net.Http.Formatting.OData.Test.EntityTypes/Employee</id>
        ///  <title />
        ///  <updated>UpdatedTime</updated>
        ///</feed></summary>
        internal static string TestFeedOfEmployee {
            get {
                return ResourceManager.GetString("TestFeedOfEmployee", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<ArrayOfstring xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices">
        ///  <element>Frank</element>
        ///  <element>Steve</element>
        ///  <element>Tom</element>
        ///  <element>Chandler</element>
        ///</ArrayOfstring></summary>
        internal static string TestListOfStrings {
            get {
                return ResourceManager.GetString("TestListOfStrings", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:duration xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">PT1H</d:duration></summary>
        internal static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:unsignedShort xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">65535</d:unsignedShort></summary>
        internal static string UInt16 {
            get {
                return ResourceManager.GetString("UInt16", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:unsignedInt xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">4294967295</d:unsignedInt></summary>
        internal static string UInt32 {
            get {
                return ResourceManager.GetString("UInt32", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:unsignedLong xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">18446744073709551615</d:unsignedLong></summary>
        internal static string UInt64 {
            get {
                return ResourceManager.GetString("UInt64", Culture);
            }
        }
        
        /// <summary>Gets localized string like: <?xml version="1.0" encoding="utf-8"?>
        ///<d:QName xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">http://www.tempuri.org:QualifiedName</d:QName></summary>
        internal static string XmlQualifiedName {
            get {
                return ResourceManager.GetString("XmlQualifiedName", Culture);
            }
        }
    }
}

