//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http.Formatting.OData {
    
    
    internal partial class SR {
        
        static System.Resources.ResourceManager resourceManager;
        
        static System.Globalization.CultureInfo resourceCulture;
        
        private SR() {
        }
        
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceManager, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("System.Net.Http.Formatting.OData.SR", typeof(SR).Assembly);
                    resourceManager = temp;
                }
                return resourceManager;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("StrictResXFileCodeGenerator", "4.0.0.0")]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>Gets localized string like: MaxReferenceDepth value must be greater than 0.</summary>
        internal static string MaxReferenceDepthLessThanZero {
            get {
                return ResourceManager.GetString("MaxReferenceDepthLessThanZero", Culture);
            }
        }
        
        /// <summary>Gets localized string like: The argument '{0}' is null or empty.</summary>
        /// <param name="param0">Parameter 0 for string: The argument '{0}' is null or empty.</param>
        internal static string ArgumentNullOrEmpty(object param0) {
            return string.Format(Culture, ResourceManager.GetString("ArgumentNullOrEmpty", Culture), param0);
        }
        
        /// <summary>Gets localized string like: The {0} does not support deserialization.</summary>
        /// <param name="param0">Parameter 0 for string: The {0} does not support deserialization.</param>
        internal static string CanNotDeserialize(object param0) {
            return string.Format(Culture, ResourceManager.GetString("CanNotDeserialize", Culture), param0);
        }
        
        /// <summary>Gets localized string like: The value of member '{0}' in type '{1}' is null. The value of a key property cannot be null.</summary>
        /// <param name="param0">Parameter 0 for string: The value of member '{0}' in type '{1}' is null. The value of a key property cannot be null.</param>
        /// <param name="param1">Parameter 1 for string: The value of member '{0}' in type '{1}' is null. The value of a key property cannot be null.</param>
        internal static string CannotSerializerKeyValueNull(object param0, object param1) {
            return string.Format(Culture, ResourceManager.GetString("CannotSerializerKeyValueNull", Culture), param0, param1);
        }
        
        /// <summary>Gets localized string like: Cannot serialize a null '{0}'.</summary>
        /// <param name="param0">Parameter 0 for string: Cannot serialize a null '{0}'.</param>
        internal static string CannotSerializerNull(object param0) {
            return string.Format(Culture, ResourceManager.GetString("CannotSerializerNull", Culture), param0);
        }
        
        /// <summary>Gets localized string like: The member '{0}' in type '{1}' can not be declared as a key.  Only members that are DataContract primitive types can be declared as a key member.</summary>
        /// <param name="param0">Parameter 0 for string: The member '{0}' in type '{1}' can not be declared as a key.  Only members that are DataContract primitive types can be declared as a key member.</param>
        /// <param name="param1">Parameter 1 for string: The member '{0}' in type '{1}' can not be declared as a key.  Only members that are DataContract primitive types can be declared as a key member.</param>
        internal static string MemberCannotBeKey(object param0, object param1) {
            return string.Format(Culture, ResourceManager.GetString("MemberCannotBeKey", Culture), param0, param1);
        }
        
        /// <summary>Gets localized string like: The '{0}' serializer cannot serialize the type '{1}'.</summary>
        /// <param name="param0">Parameter 0 for string: The '{0}' serializer cannot serialize the type '{1}'.</param>
        /// <param name="param1">Parameter 1 for string: The '{0}' serializer cannot serialize the type '{1}'.</param>
        internal static string SerializerCannotSerializeType(object param0, object param1) {
            return string.Format(Culture, ResourceManager.GetString("SerializerCannotSerializeType", Culture), param0, param1);
        }
        
        /// <summary>Gets localized string like: '{0}' cannot be serialized using the DataContractODataSerializer.</summary>
        /// <param name="param0">Parameter 0 for string: '{0}' cannot be serialized using the DataContractODataSerializer.</param>
        internal static string TypeCannotBeSerialized(object param0) {
            return string.Format(Culture, ResourceManager.GetString("TypeCannotBeSerialized", Culture), param0);
        }
        
        /// <summary>Gets localized string like: The type '{0}' can not have key members because it is either a primitive data type, enum data type or a collection type.</summary>
        /// <param name="param0">Parameter 0 for string: The type '{0}' can not have key members because it is either a primitive data type, enum data type or a collection type.</param>
        internal static string TypeCannotHaveKeyMembers(object param0) {
            return string.Format(Culture, ResourceManager.GetString("TypeCannotHaveKeyMembers", Culture), param0);
        }
        
        /// <summary>Gets localized string like: The type '{0}' does not have a member '{1}' to be used as a key member.</summary>
        /// <param name="param0">Parameter 0 for string: The type '{0}' does not have a member '{1}' to be used as a key member.</param>
        /// <param name="param1">Parameter 1 for string: The type '{0}' does not have a member '{1}' to be used as a key member.</param>
        internal static string TypeDoesNotHaveMember(object param0, object param1) {
            return string.Format(Culture, ResourceManager.GetString("TypeDoesNotHaveMember", Culture), param0, param1);
        }
        
        /// <summary>Gets localized string like: This method cannot be called for '{0}'. WriteObjectInline method can only be called for ODataEntityTypeSerializer and ODataFeedSerializer.</summary>
        /// <param name="param0">Parameter 0 for string: This method cannot be called for '{0}'. WriteObjectInline method can only be called for ODataEntityTypeSerializer and ODataFeedSerializer.</param>
        internal static string WriteObjectInlineNotSupported(object param0) {
            return string.Format(Culture, ResourceManager.GetString("WriteObjectInlineNotSupported", Culture), param0);
        }
    }
}

