//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.16832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Runtime.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.16832.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.16832")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.contoso.com/books")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.contoso.com/books", IsNullable = false)]
[DataContract]
public partial class bookstore
{

    private bookstoreBook[] bookField;

    private bookstoreBookGenre[] genresField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("book")]
    [DataMember]
    public bookstoreBook[] book
    {
        get
        {
            return this.bookField;
        }
        set
        {
            this.bookField = value;
        }
    }

    [DataMember]
    public bookstoreBookGenre[] genres
    {
        get
        {
            return this.genresField;
        }
        set
        {
            this.genresField = value;
        }
    }


}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.16832")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.contoso.com/books")]
[DataContract]
public partial class bookstoreBook
{

    private bookstoreBookTitle titleField;

    private bookstoreBookAuthor authorField;

    private decimal priceField;

    private bookstoreBookGenre genreField;

    private System.DateTime publicationdateField;

    private string iSBNField;

    /// <remarks/>
    [DataMember]
    public bookstoreBookTitle title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public bookstoreBookAuthor author
    {
        get
        {
            return this.authorField;
        }
        set
        {
            this.authorField = value;
        }
    }

    /// <remarks/>
    [DataMember]
    public decimal price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [DataMember]
    public bookstoreBookGenre genre
    {
        get
        {
            return this.genreField;
        }
        set
        {
            this.genreField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    [DataMember]
    public System.DateTime publicationdate
    {
        get
        {
            return this.publicationdateField;
        }
        set
        {
            this.publicationdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [DataMember]
    public string ISBN
    {
        get
        {
            return this.iSBNField;
        }
        set
        {
            this.iSBNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.16832")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.contoso.com/books")]
[DataContract]
public enum bookstoreBookTitle
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("The Autobiography of Benjamin Franklin")]
    [EnumMember]
    TheAutobiographyofBenjaminFranklin,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("The Confidence Man")]
    [EnumMember]
    TheConfidenceMan,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("The Gorgias")]
    [EnumMember]
    TheGorgias,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.16832")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.contoso.com/books")]
[DataContract]
public partial class bookstoreBookAuthor
{

    private string nameField;

    private string firstnameField;

    private string lastnameField;

    /// <remarks/>
    [DataMember]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("first-name")]
    [DataMember]
    public string firstname
    {
        get
        {
            return this.firstnameField;
        }
        set
        {
            this.firstnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-name")]
    [DataMember]
    public string lastname
    {
        get
        {
            return this.lastnameField;
        }
        set
        {
            this.lastnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.16832")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.contoso.com/books")]
[DataContract]
public enum bookstoreBookGenre
{

    /// <remarks/>
    [EnumMember]
    autobiography,

    /// <remarks/>
    [EnumMember]
    novel,

    /// <remarks/>
    [EnumMember]
    philosophy,
}
